development:
  encoding: utf8
  adapter: postgresql
  database: rowe-chiropractic-data
  username: <%= `whoami` %>

test:
  encoding: utf8
  pool: 10
  adapter: postgresql
  database: rowe_chiropractic_test
  username: <%= `whoami` %>
