development:
  encoding: utf8
  adapter: postgresql
  database: cms_template_prod
  username: <%= `whoami` %>

test:
  encoding: utf8
  pool: 10
  adapter: postgresql
  database: cms_template_test
  username: <%= `whoami` %>
